#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member ; the names are self explanatory
namespace Roblox_Sharp.Enums
{
    /// <summary>
    /// The asset type id of asset with id Roblox.Inventory.Api.V2.UserAssetItemModelV2.AssetId. <br/>
    /// <seealso cref="Roblox_Sharp.Endpoints.Inventory_v2"/>
    /// </summary>
    public enum AssetType : byte
    {
        Image = 1,
        TShirt = 2,
        Audio = 3,
        Mesh = 4,
        Lua = 5,
        HTML = 6,
        Text = 7,
        Hat = 8,
        Place = 9,
        Model = 10,
        Shirt = 11,
        Pants = 12,
        Decal = 13,
        Avatar = 16,
        Head = 17,
        Face = 18,
        Gear = 19,
        Badge = 21,
        GroupEmblem = 22,
        Animation = 24,
        Arms = 25,
        Legs = 26,
        Torso = 27,
        RightArm = 28,
        LeftArm = 29,
        LeftLeg = 30,
        RightLeg = 31,
        Package = 32,
        YouTubeVideo = 33,
        GamePass = 34,
        App = 35,
        Code = 37,
        Plugin = 38,
        SolidModel = 39,
        MeshPart = 40,
        HairAccessory = 41,
        FaceAccessory = 42,
        NeckAccessory = 43,
        ShoulderAccessory = 44,
        FrontAccessory = 45,
        BackAccessory = 46,
        WaistAccessory = 47,
        ClimbAnimation = 48,
        DeathAnimation = 49,
        FallAnimation = 50,
        IdleAnimation = 51,
        JumpAnimation = 52,
        RunAnimation = 53,
        SwimAnimation = 54,
        WalkAnimation = 55,
        PoseAnimation = 56,
        LocalizationTableManifest = 59,
        LocalizationTableTranslation = 60,
        EmoteAnimation = 61,
        Video = 62,
        TexturePack = 63,
        TShirtAccessory = 64,
        ShirtAccessory = 65,
        PantsAccessory = 66,
        JacketAccessory = 67,
        SweaterAccessory = 68,
        ShortsAccessory = 69,
        LeftShoeAccessory = 70,
        RightShoeAccessory = 71,
        DressSkirtAccessory = 72,
        FontFamily = 73,
        FontFace = 74,
        MeshHiddenSurfaceRemoval = 75,
        EyebrowAccessory = 76,
        EyelashAccessory = 77,
        MoodAnimation = 78,
        DynamicHead = 79,
        CodeSnippet = 80,
        AdsVideo = 81,
        OtaUpdate = 82,
        Screenshot = 83
    }
}
