# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Roblox_Sharp CI


on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - stable
    paths: 
      - '**.cs'
      - '**.csproj'
      
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build Project
      run: dotnet build ./SRC/Roblox_Sharp.csproj
    - name: Build Solution
      run: dotnet build  ./SRC/Roblox_Sharp.sln
    - name: Test
      run: dotnet test ./SRC/Roblox_Sharp.sln
      
