#Builds Roblox_Sharp and also Tests functionality of objects and json deserialization
name: Framework Functionality

on:
    workflow_dispatch:
    push:

defaults:
    run:
        working-directory: "lib"

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Build Roblox_Sharp
              run: dotnet build -c Debug Roblox_Sharp.sln

            - name: Upload Roblox_Sharp Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: built-project
                  path: lib/bin/Debug/

            - name: Object Functionality Tests
              run: dotnet test -c Debug --no-build --filter xUnitTests=Object_Functionality

            - name: JSON Deserialization Tests
              run: dotnet test -c Debug --no-build --filter xUnitTests=Deserialization
