#Builds Roblox_Sharp and also Tests functionality of objects
name: Framework Functionality

on:
    workflow_dispatch:
    push:

defaults:
    run:
        working-directory: "src"

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Build Roblox_Sharp
              run: dotnet build -c Debug Roblox_Sharp.sln

            - name: Model Functionality
              run: dotnet test -c Debug --no-build --filter Models=Model_Functionality

              continue-on-error: true

            - name: JSON Serialization
              run: dotnet test -c Debug --no-build --filter Models=Serialization

              continue-on-error: true

            - name: JSON Deserialization
              run: dotnet test -c Debug --no-build --filter Models=Deserialization
