# Tests the Web requests that get rate limitted easily
name: Long Web Integration

on:
    workflow_dispatch:

    pull_request:
        types: [opened]
        branches:
            - stable
            - main
        paths:
            - "**.cs"
            - "**.csproj"

defaults:
    run:
        working-directory: "lib"

jobs:
    Long-Integration-Tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Download Roblox_Sharp Artifact
              uses: actions/download-artifact@v4
              with:
                  name: built-project
                  path: lib/bin/Debug/

            - name: Long Integration Tests
              run: dotnet test -c Debug --no-build --filter xUnitTests=Long_Integration
