#Tests the Web requests that are lenient with the rate limits
name: Web Integration

on:
    push:
        branches:
            - stable
            - main
        paths:
            - "**.cs"
            - "**.csproj"

defaults:
    run:
        working-directory: "lib"

jobs:
    Short-Integration-Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Download Roblox_Sharp Artifact
              uses: actions/download-artifact@v4
              with:
                  name: built-project
                  path: lib/bin/Debug/

            - name: Short Integration Tests
              run: dotnet test -c Debug --no-build --filter xUnitTests=Integration
