#Tests the Web requests that are lenient with the rate limits
name: Web Integration

on:
  workflow_dispatch:

  push:
    branches:
      - stable
      - main
    paths:
    - '**.cs'
    - '**.csproj'

defaults:
  run:
    working-directory: "lib"

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build Roblox_Sharp
        run:  dotnet build -c Debug Roblox_Sharp.sln

      - name: Short Integration Tests
        run: dotnet test -c Debug --no-build --filter xUnitTests=Integration