#Tests the Web requests that are lenient with the rate limits
name: Web Integration

on:
    push:
        branches:
            - stable
            - main
        paths:
            - "**.cs"
            - "**.csproj"

defaults:
    run:
        working-directory: "xUnitTests"

jobs:
    Short-Integration-Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Download Cached Roblox_Sharp
              uses: actions/cache@v4
              with:
                  path: "**/bin/Debug/"
                  key: ${{ runner.os }}-build-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            - name: Short Integration Tests
              run: dotnet test -c Debug --no-build --filter xUnitTests=Integration
