#Tests the Web requests
name: Web Integration

on:
    workflow_dispatch:
    pull_request:
        types: [opened, synchronize, reopened]
        branches: [main, unstable]
        paths:
            - "**.cs"
            - "**.csproj"
    push:
        branches: [unstable]
        paths:
            - "**.cs"
            - "**.csproj"
defaults:
    run:
        working-directory: "src"

jobs:
    Integration-Tests:
        name: Integration

        concurrency:
            group: Integration
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8s.x"

            - name: Build Roblox_Sharp
              run: dotnet build

            - name: Short Integration Tests
              run: dotnet test -c Debug --no-build  --filter Endpoints=Integration

              continue-on-error: true

            - name: Long Integration Tests
              run: dotnet test -c Debug --no-build --filter Endpoints=Long_Integration
