#Tests the Web requests
name: Web Integration

on:
    workflow_run:
        workflows: [Framework Functionality]
        types: [completed]
        branches: [stable, main]
    # push:
    #    branches:
    #       - stable
    #      - main
    # paths:
    #    - "**.cs"
    #   - "**.csproj"

jobs:
    Integration-Tests:
        name: Short Integration Tests

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"
            - uses: actions/cache@v4
              with:
                  path: "**/bin/Debug/"
                  key: ${{ runner.os }}-build-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            - name: Short Integration Tests
              run: dotnet test -c Debug lib/  --filter xUnitTests=Integration

    Long-Integration-Tests:
        name: Rate Limitted Integration Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"
            - name: Download Roblox_Sharp
              uses: actions/cache@v4
              with:
                  path: "**/bin/Debug/"
                  key: ${{ runner.os }}-build-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            - name: Long Integration Tests
              run: dotnet test -c Debug lib/ --no-build --filter xUnitTests=Long_Integration
