#Tests the Web requests
name: Web Integration

on:
    workflow_run:
        workflows: [Framework Functionality]
        types: [completed]
        branches: [stable, main]
    # push:
    #    branches:
    #       - stable
    #      - main
    # paths:
    #    - "**.cs"
    #   - "**.csproj"

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Download Cached Roblox_Sharp
              uses: actions/cache@v4
              with:
                  path: "**/bin/Debug/"
                  key: ${{ runner.os }}-build-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-build-

            # - run: dotnet build lib\
            - run: dotnet build xUnitTests -c Debug xUnitTests\
            - uses: actions/upload-artifact@v4
              with:
                  name: tests
                  path: "**/bin/Debug/"

    Integration-Tests:
        name: Short Integration Tests
        needs: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v4 # Artifact Downloading
              with:
                  name: tests
                  path: "**/bin/Debug/"
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Short Integration Tests
              run: dotnet test -c Debug lib/ --no-build --filter xUnitTests=Integration

    Long-Integration-Tests:
        name: Rate Limitted Integration Tests
        needs: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"
            - uses: actions/download-artifact@v4
              with:
                  name: tests
                  path: "**/bin/Debug/"

            - name: Long Integration Tests
              run: dotnet test -c Debug lib/ --no-build --filter xUnitTests=Long_Integration
